GET http://localhost:3000/v1/test

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
POST http://localhost:3000/routes/
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "ChIJ55QOAlSjHpURKMMYZKgJpzg",
  "destination_id": "ChIJnzWK_Fp3GZURj1PdYEehmck"
}

### Requisições referentes ao mapa

### Pegar o place_id
GET http://localhost:3000/places?text=aeroporto regional hugo cantergiani, caxias do sul

### Pegar direções entre 2 pontos
GET http://localhost:3000/directions?originId=ChIJ55QOAlSjHpURKMMYZKgJpzg&destinationId=ChIJnzWK_Fp3GZURj1PdYEehmck